/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Dice: typeof import('./src/components/Dice.vue')['default']
    DiceRoller: typeof import('./src/components/DiceRoller.vue')['default']
    GoblinButton: typeof import('./src/components/GoblinButton.vue')['default']
    GoblinCard: typeof import('./src/components/GoblinCard.vue')['default']
    GoblinImage: typeof import('./src/components/GoblinImage.vue')['default']
    IGameIconsGoblin: typeof import('~icons/game-icons/goblin')['default']
    JoinTableModal: typeof import('./src/components/JoinTableModal.vue')['default']
    PlayerCard: typeof import('./src/components/PlayerCard.vue')['default']
    PlayerGrid: typeof import('./src/components/PlayerGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarToggle: typeof import('./src/components/SidebarToggle.vue')['default']
    TableChat: typeof import('./src/components/TableChat.vue')['default']
    TableDiceRoller: typeof import('./src/components/TableDiceRoller.vue')['default']
  }
}
